# Project Information
site_name: NCI-RBL Dockers
site_author: Wilfried Guiblet, Ph.D. and Vishal Koparde, Ph.D.
site_description: >-
  A repository of Dockers and NextFlow workflows for the NCI-RBL

# Repository
repo_name: NCI-RBL/Dockers
repo_url: https://github.com/NCI-RBL/Dockers
edit_uri: https://github.com/NCI-RBL/Dockers/edit/main/docs/

# Copyright
copyright: Copyright &copy; 2022 CCBR

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - toc.integrate 
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  logo: https://ccbr.github.io/HowTos/assets/images/doc-book.svg
  favicon: assets/images/favicon.png

# Plugins
plugins:
  - search
  - git-revision-date
  - minify:
      minify_html: true


# Customization
extra:
  social:
    - icon: fontawesome/solid/users
      link: http://bioinformatics.cancer.gov
    - icon: fontawesome/brands/github
      link: https://github.com/CCRGeneticsBranch
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/orgs/nciccbr/repositories
  version:
    provider: mike


# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page Tree
nav:
  - Intro : index.md
  - MOP2:
    - Description: MOP2/descript.md
    - Initialize: MOP2/init.md
    - Run: MOP2/run.md
  - DTEG:
    - Description: DTEG/descript.md
    - Initialize: DTEG/init.md
    - Run: DTEG/run.md
  - ISOMIR:
    - Description: ISOMIR/descript.md
    - Initialize: ISOMIR/init.md
    - Run: ISOMIR/run.md
  - RiboFootPrint:
    - Description: RiboFootPrint/descript.md
    - Initialize: RiboFootPrint/init.md
    - Run: RiboFootPrint/run.md
  - iCLIP:
    - Description: iCLIP/descript.md
    - Initialize: iCLIP/init.md
    - Run: iCLIP/run.md
  - eCLIP:
    - Workflow : eCLIP/eCLIP_workflow.md
