FROM wilfriedguiblet/dteg:v0.1

ENV TAG="v0.2"

WORKDIR /opt2
COPY python_dependencies.txt ./

RUN pip3 install --no-cache-dir -r python_dependencies.txt
COPY 80S_basic_workflow.py ./
COPY StarAlign_main.py ./
COPY makeavggene_main.py ./
COPY rphelper.py ./
COPY densebuilder_main.py ./
COPY GFF/ ./

RUN chmod a+x /opt2/80S_basic_workflow.py && \
    chmod a+x /opt2/StarAlign_main.py && \
    chmod a+x /opt2/makeavggene_main.py && \
    chmod a+x /opt2/rphelper.py && \
    chmod a+x /opt2/densebuilder_main.py && \
    chmod a+x /opt2/GFF/*

ENV PATH=/opt2/:$PATH

# cleanup etc
COPY Dockerfile.${TAG} /opt2/Dockerfile.${TAG}
RUN chmod a+rX /opt2/Dockerfile.${TAG}
WORKDIR /data2
RUN apt-get clean

# details
LABEL maintainer="guibletwm@nih.gov"
LABEL github_handle="wilfriedguiblet"
ARG BUILD_DATE
LABEL build_date=$BUILD_DATE
