FROM wilfriedguiblet/dteg:v0.3

ENV TAG="v0.4"

# install faToTwoBit
WORKDIR /opt2
RUN wget --no-check-certificate http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/faToTwoBit
RUN chmod a+x /opt2/faToTwoBit


# cleanup etc
COPY Dockerfile.${TAG} /opt2/Dockerfile.${TAG}
RUN chmod a+rX /opt2/Dockerfile.${TAG}
WORKDIR /data2
RUN apt-get clean

# details
LABEL maintainer="guibletwm@nih.gov"
LABEL github_handle="wilfriedguiblet"
ARG BUILD_DATE
LABEL build_date=$BUILD_DATE
