FROM wilfriedguiblet/isomir:v0.2

ENV TAG="v0.3"

WORKDIR /opt2

# Add additional scripts

COPY adaptor_remove_lab_new8nt.c /opt2
COPY adaptor_remove_illumina_v5.c /opt2
COPY adaptor_remove_NEB_v2.c /opt2
COPY RPM_summary.R /opt2
RUN chmod a+x /opt2/adaptor_remove_lab_new8nt.c
RUN chmod a+x /opt2/adaptor_remove_illumina_v5.c
RUN chmod a+x /opt2/adaptor_remove_NEB_v2.c
RUN chmod a+x /opt2/RPM_summary.R

# Compile C scripts

RUN gcc /opt2/adaptor_remove_lab_new8nt.c -o /opt2/adaptor_remove_lab_new8nt.exe
RUN gcc /opt2/adaptor_remove_illumina_v5.c -o /opt2/adaptor_remove_illumina_v5.exe
RUN gcc /opt2/adaptor_remove_NEB_v2.c -o /opt2/adaptor_remove_NEB_v2.exe
RUN chmod a+x /opt2/adaptor_remove_lab_new8nt.exe
RUN chmod a+x /opt2/adaptor_remove_illumina_v5.exe
RUN chmod a+x /opt2/adaptor_remove_NEB_v2.exe


# cleanup etc
COPY Dockerfile.${TAG} /opt2/Dockerfile.${TAG}
RUN chmod a+rX /opt2/Dockerfile.${TAG}
WORKDIR /data2
RUN apt-get clean

# details
LABEL maintainer="guibletwm@nih.gov"
LABEL github_handle="wilfriedguiblet"
ARG BUILD_DATE
LABEL build_date=$BUILD_DATE
