FROM nciccbr/ccbr_ubuntu_base_20.04:v2.1

ENV TAG="v0.1"

#Copy scripts 
WORKDIR /opt2
COPY scripts /opt2
RUN chmod a+x /opt2/adaptor_remove_Qiagen_v3
ENV PATH=/opt2/:$PATH

# cleanup etc
COPY Dockerfile.${TAG} /opt2/Dockerfile.${TAG}
RUN chmod a+rX /opt2/Dockerfile.${TAG}
WORKDIR /data2
RUN apt-get clean

# details
LABEL maintainer="guibletwm@nih.gov"
LABEL github_handle="wilfriedguiblet"
ARG BUILD_DATE
LABEL build_date=$BUILD_DATE
