
# Global parameters

workdir: '/data/RBL_NCI/WilTemp/iCLIP/' # working directory
tempdir: '/data/RBL_NCI/WilTemp/iCLIP/temp/' # Temp directory. 

sourcedir: '/opt2/' # source directory. Do NOT change if using containers.


rawfilesnames: # list of raw files names
  - 'PARiCLIP_mRO3_S1_R1_001'
  #- '2_PARiCLIP_mRO2_S1_R1_001'
  #- 'toyfile'
  #- 'toyfile2'

rawdir: '/data/RBL_NCI/WilTemp/iCLIP/rawfiles/' # directory for rawfiles

samplenames:
  - 'YKO_Clip3'
  - 'Y1KO_Clip3'
  - 'Y3KO_Clip3'
  - 'Ro_Clip3'
  - 'Control_Clip3'

contrasts:
  - ['YKO_Clip3', 'Ro_Clip3']
  - ['Y1KO_Clip3', 'Ro_Clip3']
  - ['Y3KO_Clip3', 'Ro_Clip3']


reference: "" # reference organism ["hg38","mm10"]
include_rRNA: "Y" # whether to include refseq rRNA's in annotations ["Y", "N"]
peakid: "ALL"
#splicejunction: "N" #whether to include splice junctions in peak calls for DE_METHOD MANORM or DIFFBIND ["Y", "N"]
#AnnoAnchor: "max_total" #whether annotations for spliced peaks will be based on either 5' most region or region with max reads ["max","5prime"]
mincount: 3 #minimum number of reads to count as a peak [1,2,3]
DEmethod: "NONE" #DE method ["NONE", "MANORM", "DIFFBIND"]
mismatch: 1 #required for multiplexed samples, number of bp mismatches allowed in demultiplexing [1,2,3]
min_reads_mapped: 0.5 #minimum percent of reads that should be mapped; IE .5 for 50% of all reads must be mapped [0.5]
umiSeparator: "rbc:" #required for nondemultiplexed samples to determine delimiter for deduplication [":", "_", "rbc:"]
multiplexflag: "Y" #whether samples are multiplexed ["Y","N"]
MANormWidth: 50 #Width of window to calculate read density. [any integer >1; default 50]
MNormDistance: 25 #Summit-to-summit distance cutoff for common peaks. [ any integer >1; default MANormWidth/2]

containerDir: "/data/CCBR_Pipeliner/iCLIP/container"
fastq_val: "/data/CCBR_Pipeliner/iCLIP/bin/fastQValidator"

#########################################################################################
# Index paths
#########################################################################################
hg38:
  stardir: '/data/CCBR_Pipeliner/iCLIP/index/active/2022_0505/hg38/index'
  stargtf: '/data/CCBR_Pipeliner/iCLIP/index/active/2022_0505/hg38/ref/gencode.v32.annotation.gtf'
  gencodepath: '/data/CCBR_Pipeliner/iCLIP/ref/annotations/hg38/Gencode_V32/fromGencode/gencode.v32.annotation.gtf.txt'
  refseqpath: '/data/CCBR_Pipeliner/iCLIP/ref/annotations/hg38/NCBI_RefSeq/GCF_000001405.39_GRCh38.p13_genomic.gtf.txt'
  canonicalpath: '/data/CCBR_Pipeliner/iCLIP/ref/annotations/hg38/Gencode_V32/fromUCSC/KnownCanonical/KnownCanonical_GencodeM32_GRCh38.txt'
  intronpath: '/data/CCBR_Pipeliner/iCLIP/ref/annotations/hg38/Gencode_V32/fromUCSC/KnownGene/KnownGene_GencodeV32_GRCh38_introns.bed'
  rmskpath: '/data/CCBR_Pipeliner/iCLIP/ref/annotations/hg38/repeatmasker/rmsk_GRCh38.txt'
  aliaspath: '/data/CCBR_Pipeliner/iCLIP/ref/annotations/hg38/hg38.chromAlias.txt'
  additionalannopath: '/data/CCBR_Pipeliner/iCLIP/ref/annotations/hg38/additional_anno/'
mm10:
  stardir: '/data/CCBR_Pipeliner/iCLIP/index/active/2022_0505/mm10/index'
  stargtf: '/data/CCBR_Pipeliner/iCLIP/index/active/2022_0505/mm10/ref/gencode.vM23.annotation.gtf'
  gencodepath: '/data/CCBR_Pipeliner/iCLIP/ref/annotations/mm10/Gencode_VM23/fromGencode/gencode.vM23.annotation.gtf.txt'
  refseqpath: '/data/CCBR_Pipeliner/iCLIP/ref/annotations/mm10/NCBI_RefSeq/GCF_000001635.26_GRCm38.p6_genomic.gtf.txt'
  canonicalpath: '/data/CCBR_Pipeliner/iCLIP/ref/annotations/mm10/Gencode_VM23/fromUCSC/KnownCanonical/KnownCanonical_GencodeM23_GRCm38.txt'
  intronpath: '/data/CCBR_Pipeliner/iCLIP/ref/annotations/mm10/Gencode_VM23/fromUCSC/KnownGene/KnownGene_GRCm38_introns.bed'
  rmskpath: '/data/CCBR_Pipeliner/iCLIP/ref/annotations/mm10/repeatmasker/rmsk_GRCm38.txt'
  aliaspath: '/data/CCBR_Pipeliner/iCLIP/ref/annotations/mm10/mm10.chromAlias.txt'
  additionalannopath: '/data/CCBR_Pipeliner/iCLIP/ref/annotations/mm10/additional_anno/'

#########################################################################################
# Manifests
#########################################################################################
manifests:
  samples: '/data/RBL_NCI/WilTemp/iCLIP/manifests/samples.tsv'
  multiplex: '/data/RBL_NCI/WilTemp/iCLIP/manifests/multiplex.tsv'
  barcode: '/data/RBL_NCI/WilTemp/iCLIP/manifests/clip3_barcode_manifest.txt'

#########################################################################################
# QC barcode parameters
#########################################################################################
qc_barcode:
  start_pos: 6 # or 4. 
  barcode_length: 6 #
  memory: '75g'
  threads: 64
  time: '00-04:00:00'
  mpid: 'clip3' # Multiplex ID

#########################################################################################
# DeMultiplex parameters
#########################################################################################
demultiplex:
  memory: '32g'
  threads: 64
  time: '00-05:00:00'
  gres: lscratch:800
  filterlength: 20 #minimum read length to include in analysis [any int >20]
  phredQuality: 20 #minimum quality score for 3’ end trimming



#########################################################################################
# STAR parameters
#########################################################################################
STAR:
  threads: 32
  alignEndsType: "Local" #type of read ends alignment ["Local", "EndToEnd", "Extend5pOfRead1", "Extend5pOfReads12"]
  alignIntronMax: 50000 #maximum intron length
  alignSJDBoverhangMin: 3 # minimum overhang value for annotated spliced junctions
  alignSJoverhangMin: 5 # minimum overhang value for non-cannonical splied junctions
  alignTranscriptsPerReadNmax: 10000 #max number of different alignments per read to consider [int>0]
  alignWindowsPerReadNmax: 10000 #max number of windows per read [int>0]
  limitOutSJcollapsed: 1000000 # max number of collapsed junctions [int>0]
  outFilterMatchNmin: 15 # alignment will be output only if the number of matched bases is higher than or equal to this value.
  outFilterMatchNminOverLread: 0.9 #alignment will be output only if the number of matched bases is >= to value; normalized to sum of mates’ lengths for paired-end reads
  outFilterMismatchNmax: 999 #alignment will be output only if it has no more mismatches than this value.
  outFilterMismatchNoverReadLmax: 0.04 #alignment will be output only if its ratio of mismatches to *read* length is less than or equal to this value.
  outFilterMultimapNmax: 10000 #max number of multiple alignments allowed for a read: if exceeded, the read is considered unmapped
  outFilterMultimapScoreRange: 0 #the score range below the maximum score for multimapping alignments
  outFilterScoreMin: 0 #alignment will be output only if its score is higher than or equal to this value.
  outFilterType: "Normal" #type of filtering ["Normal", "BySJout"]
  outSAMattributes: "All" #a string of desired SAM attributes, in the order desired for the output SAM
  outSAMunmapped: "None" #output of unmapped reads in the SAM format ["None", "Within"]
  outSJfilterCountTotalMin: "3,1,1,1" #minimum total (multi-mapping+unique) read count per junction for: (1) non-canonical motifs, (2) GT/AG and CT/AC motif, (3) GC/AG and CT/GC motif, (4) AT/AC and GT/AT motif
  outSJfilterOverhangMin: "30,12,12,12" #minimum overhang length for splice junctions on both sides for: (1) non-canonical motifs, (2) GT/AG and CT/AC motif, (3) GC/AG and CT/GC motif, (4) AT/AC and GT/AT motif
  outSJfilterReads: "All" #which reads to consider for collapsed splice junctions output ["All", "Unique"]
  seedMultimapNmax: 10000 #only pieces that map fewer than this value are utilized in the stitching procedure [int>0]
  seedNoneLociPerWindow: 20 #max number of one seed loci per window [int>0]
  seedPerReadNmax: 10000 #max number of seeds per read
  seedPerWindowNmax: 500 #max number of seeds per window
  sjdbScore: 2 #extra alignment score for alignmets that cross database junctions
  winAnchorMultimapNmax: 10000 #max number of loci anchors are allowed to map to
  quantmod: 'TranscriptomeSAM' #additionnal alignment on transcriptome
  bamlimit: '50297600554'


#########################################################################################
# featureCounts parameters
#########################################################################################

featureCounts:
  threads: '8'

#########################################################################################
# QC_Screen_Validator parameters
#########################################################################################

QC_Screen_Validator:
  threads: '8'
