FROM nciccbr/ccbr_ubuntu_22.04:v4
#FROM continuumio/conda-ci-linux-64-python2.7  

ENV TAG="v0.1"
WORKDIR /opt2

# Install miniconda
ENV CONDA_DIR /opt/conda

RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && \
     /bin/bash ~/miniconda.sh -b -p /opt/conda

ENV PATH=$CONDA_DIR/bin:$PATH


RUN conda config  --append channels conda-forge && \
    conda config  --append channels bioconda && \
    conda config  --append channels conda-forge && \
    conda config  --set restore_free_channel true

RUN conda create -n py27k anaconda python=2.7

# Make RUN commands use the new environment:
#SHELL ["conda", "run", "-n", "py27k", "/bin/bash", "-c"]

SHELL ["conda", "install", "-n", "py27k", "bioconda::bioconductor-clipper"]
SHELL ["conda", "install", "-n", "py27k", "bedtools=2.27.1"]
SHELL ["conda", "install", "-n", "py27k", "cutadapt=1.14"]
SHELL ["conda", "install", "-n", "py27k", "eclipdemux=0.0.1"]
SHELL ["conda", "install", "-n", "py27k", "fastqc=0.11.8"]
SHELL ["conda", "install", "-n", "py27k", "fastq-tools=0.8"]
#SHELL ["conda", "install", "-n", "py27k", "perl=5.10.1"]
#SHELL ["conda", "install", "-n", "py27k", "perl"]
SHELL ["conda", "install", "-n", "py27k", "bioconda::perl-statistics-basic=1.6611"]
SHELL ["conda", "install", "-n", "py27k", "bioconda::perl-statistics-distributions=1.02"]
SHELL ["conda", "install", "-n", "py27k", "bioconda::perl-statistics-r=0.34"]
SHELL ["conda", "install", "-n", "py27k", "conda-forge::r-base=3.3.2"]
SHELL ["conda", "install", "-n", "py27k", "bioconda::pysam=0.15.4"]
SHELL ["conda", "install", "-n", "py27k", "bioconda::numpy=1.16.5"]
SHELL ["conda", "install", "-n", "py27k", "bioconda::samtools=1.6"]
SHELL ["conda", "install", "-n", "py27k", "bioconda::star=2.7.6a"]
SHELL ["conda", "install", "-n", "py27k", "anaconda::seaborn"]
SHELL ["conda", "install", "-n", "py27k", "iuc/label/outdated::ucsc_tools"]
SHELL ["conda", "install", "-n", "py27k", "bioconda::umi_tools=1.0.0"]
SHELL ["conda", "install", "-n", "py27k", "brittainhard::cwlref-runner=1.0"]
SHELL ["conda", "install", "-n", "py27k", "conda-forge::cwltool=1.0.20180306140409"]
SHELL ["conda", "install", "-n", "py27k", "bioconda::cwltest=1.0.20180413145017"]
SHELL ["conda", "install", "-n", "py27k", "bioconda::galaxy-lib=17.9.3"]
SHELL ["conda", "install", "-n", "py27k", "bioconda::toil"]

RUN

#RUN bedtools 

#RUN conda install bioconda::bioconductor-clipper

# Install awkde
#RUN git clone https://github.com/mennthor/awkde && \
#    pip install -e ./awkde

# Install SMsplice
#RUN git clone https://github.com/kmccue/SMsplice/ && \
#    cd SMsplice && \
#    conda env create -f environment.yml 

#SHELL ["conda", "run", "-n", "SMsplice", "/bin/bash", "-c"]
#ENTRYPOINT ["pip", "install", "-e", "./awkde"]


#RUN pip install -e ./awkde



# cleanup etc
#COPY Dockerfile.${TAG} /opt2/Dockerfile.${TAG}
#RUN chmod a+rX /opt2/Dockerfile.${TAG}
#WORKDIR /data2
#RUN apt-get clean

# details
LABEL maintainer="guibletwm@nih.gov"
LABEL github_handle="wilfriedguiblet"
ARG BUILD_DATE
LABEL build_date=$BUILD_DATE
