FROM nciccbr/ccbr_ubuntu_base_20.04:v2.1

ENV TAG="v0.1"

WORKDIR /opt2

# Download ViennaRNA 2.5.1

RUN wget https://www.tbi.univie.ac.at/RNA/download/sourcecode/2_5_x/ViennaRNA-2.5.1.tar.gz && \
    tar -zxvf ViennaRNA-2.5.1.tar.gz && \
    cd ViennaRNA-2.5.1 && \
    ./configure && \
    make && \
    make install


# cleanup etc
COPY Dockerfile.${TAG} /opt2/Dockerfile.${TAG}
RUN chmod a+rX /opt2/Dockerfile.${TAG}
WORKDIR /data2
RUN apt-get clean

# details
LABEL maintainer="guibletwm@nih.gov"
LABEL github_handle="wilfriedguiblet"
ARG BUILD_DATE
LABEL build_date=$BUILD_DATE
