FROM nciccbr/ccbr_baser:latest
ENV TAG="v0.1"

# install FRASER
RUN Rscript -e 'BiocManager::install("FRASER")'
RUN Rscript -e 'BiocManager::install("TxDb.Hsapiens.UCSC.hg38.knownGene")'
RUN Rscript -e 'BiocManager::install("org.Hs.eg.db)")'

WORKDIR /opt2
COPY FRASER_ANALYSIS.r ./
RUN chmod a+x /opt2/FRASER_ANALYSIS.r
ENV PATH=/opt2/:$PATH

# cleanup etc
COPY Dockerfile.${TAG} /opt2/Dockerfile.${TAG}
RUN chmod a+rX /opt2/Dockerfile.${TAG}
WORKDIR /data2
RUN apt-get clean

# details
LABEL maintainer="guibletwm@nih.gov"
LABEL github_handle="wilfriedguiblet"
ARG BUILD_DATE
LABEL build_date=$BUILD_DATE

