FROM nciccbr/ccbr_baser:latest
ENV TAG="v0.1"

# install FRASER
RUN Rscript -e 'BiocManager::install("FRASER")'

# cleanup etc
RUN chmod a+rX /opt2/Dockerfile.${TAG}
WORKDIR /data2
RUN apt-get clean

# details
LABEL maintainer="guibletwm@nih.gov"
LABEL github_handle="wilfriedguiblet"
ARG BUILD_DATE
LABEL build_date=$BUILD_DATE


