FROM wilfriedguiblet/iclip:v3.0.2

ENV TAG="v0.3"

ENV PATH=$CONDA_DIR/bin:$PATH

# Update more permissions

RUN chmod 774 -R /opt2/fqscreen_rrna_config.conf && \
    chmod 774 -R /opt2/annotation_config.txt && \
    chmod 774 -R /opt2/nextflow.parameters.yaml && \
    chmod 774 -R /opt2/multiqc_config.yaml && \
    chmod 774 -R /opt2/fqscreen_species_config.conf

# Add R dependencies

RUN Rscript -e 'install.packages("argparse", repos = "http://cran.us.r-project.org")' && \
    Rscript -e 'install.packages("DescTools", repos = "http://cran.us.r-project.org")' && \
    Rscript -e 'install.packages("rmarkdown", repos = "http://cran.us.r-project.org")' && \
    Rscript -e 'install.packages("stringr", repos = "http://cran.us.r-project.org")' && \
    Rscript -e 'install.packages("dplyr", repos = "http://cran.us.r-project.org")' && \
    Rscript -e 'install.packages("rtracklayer", repos = "http://cran.us.r-project.org")' && \
    Rscript -e 'install.packages("VariantAnnotation", repos = "http://cran.us.r-project.org")' && \
    Rscript -e 'install.packages("ggplot2", repos = "http://cran.us.r-project.org")' && \
    Rscript -e 'install.packages("viridis", repos = "http://cran.us.r-project.org")' && \
    Rscript -e 'install.packages("edgeR", repos = "http://cran.us.r-project.org")' && \
    Rscript -e 'install.packages("GenomicFeatures", repos = "http://cran.us.r-project.org")' && \
    Rscript -e 'install.packages("rtracklayer", repos = "http://cran.us.r-project.org")' && \
    Rscript -e 'install.packages("matrixStats", repos = "http://cran.us.r-project.org")' && \
    Rscript -e 'install.packages("plyr", repos = "http://cran.us.r-project.org")' && \
    Rscript -e 'install.packages("tidyr", repos = "http://cran.us.r-project.org")' && \
    Rscript -e 'install.packages("fitdistrplus", repos = "http://cran.us.r-project.org")' && \
    Rscript -e 'install.packages("stringr", repos = "http://cran.us.r-project.org")' && \
    Rscript -e 'install.packages("data.table", repos = "http://cran.us.r-project.org")' && \
    Rscript -e 'install.packages("reshape", repos = "http://cran.us.r-project.org")' && \
    Rscript -e 'install.packages("knitr", repos = "http://cran.us.r-project.org")' && \
    Rscript -e 'install.packages("stringi", repos = "http://cran.us.r-project.org")' && \
    Rscript -e 'install.packages("BSgenome", repos = "http://cran.us.r-project.org")' && \
    Rscript -e 'install.packages("biomaRt", repos = "http://cran.us.r-project.org")' && \
    Rscript -e 'install.packages("plotly", repos = "http://cran.us.r-project.org")' && \
    Rscript -e 'install.packages("GenomicRanges", repos = "http://cran.us.r-project.org")' && \
    Rscript -e 'install.packages("RColorBrewer", repos = "http://cran.us.r-project.org")' && \
    Rscript -e 'install.packages("gplots", repos = "http://cran.us.r-project.org")' && \
    Rscript -e 'install.packages("ggpubr", repos = "http://cran.us.r-project.org")' && \
    Rscript -e 'install.packages("circlize", repos = "http://cran.us.r-project.org")' && \
    Rscript -e 'install.packages("regioneR", repos = "http://cran.us.r-project.org")' && \
    Rscript -e 'install.packages("scales", repos = "http://cran.us.r-project.org")' 


# Upgrade numpy

RUN pip install numpy --upgrade

# cleanup etc
COPY Dockerfile.${TAG} /opt2/Dockerfile.${TAG}
RUN chmod a+rX /opt2/Dockerfile.${TAG}
WORKDIR /data2
RUN apt-get clean

# details
LABEL maintainer="guibletwm@nih.gov"
LABEL github_handle="wilfriedguiblet"
ARG BUILD_DATE
LABEL build_date=$BUILD_DATE
