FROM wilfriedguiblet/ctk:v0.1 

ENV TAG="v0.1"

ENV PATH=$CONDA_DIR/bin:$PATH
RUN conda install -c bioconda subread


# cleanup etc
COPY Dockerfile.${TAG} /opt2/Dockerfile.${TAG}
RUN chmod a+rX /opt2/Dockerfile.${TAG}
WORKDIR /data2
RUN apt-get clean

# details
LABEL maintainer="guibletwm@nih.gov"
LABEL github_handle="wilfriedguiblet"
ARG BUILD_DATE
LABEL build_date=$BUILD_DATE
