FROM wilfriedguiblet/iclip:v3.0.1  

ENV TAG="v0.2"

# Copy custom scripts

COPY config/ /opt2/
COPY workflow/scripts/ /opt2/

RUN chmod 774  /opt2/02_barcode_qc.R && \
    chmod 774 /opt2/03_qc_report.Rmd  && \
    chmod 774 /opt2/03_qc_unmapped_check.sh  && \
    chmod 774 /opt2/04_annotation.R  && \
    chmod 774 /opt2/05_countmerger.py  && \
    chmod 774 /opt2/AnnotationFormat.py  && \
    chmod 774 /opt2/06_annotation.Rmd  && \
    chmod 774 /opt2/07_DIFFBIND_Process.R  && \
    chmod 774 /opt2/07_DIFFBIND_PreProcess.R  && \
    chmod 774 /opt2/08_MAnormAnnotation.Rmd 


ENV PATH=$CONDA_DIR/bin:$PATH

RUN conda install -c r r-essentials



# Add R dependencies

RUN Rscript -e 'install.packages("data.table", repos = "http://cran.us.r-project.org") '&& \
    Rscript -e 'install.packages("dplyr", repos = "http://cran.us.r-project.org")'

# cleanup etc
COPY Dockerfile.${TAG} /opt2/Dockerfile.${TAG}
RUN chmod a+rX /opt2/Dockerfile.${TAG}
WORKDIR /data2
RUN apt-get clean

# details
LABEL maintainer="guibletwm@nih.gov"
LABEL github_handle="wilfriedguiblet"
ARG BUILD_DATE
LABEL build_date=$BUILD_DATE
